create table if not exists public.equipment_proposals (
  id bigint generated by default as identity primary key,
  inventory_id uuid not null references public.inventory(id) on delete cascade,
  configuration text not null,
  file_name text not null,
  storage_path text not null unique,
  public_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inventory_id)
);

alter table public.equipment_proposals enable row level security;

drop policy if exists "Public equipment proposals are readable" on public.equipment_proposals;
create policy "Public equipment proposals are readable"
  on public.equipment_proposals for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('equipment-proposals', 'equipment-proposals', true)
on conflict (id) do update set public = true;
