create table if not exists public.equipment_brochures (
  id bigint generated by default as identity primary key,
  model_key text not null unique,
  model_name text not null,
  file_name text not null,
  storage_path text not null unique,
  public_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.equipment_brochures enable row level security;

drop policy if exists "Public equipment brochures are readable" on public.equipment_brochures;
create policy "Public equipment brochures are readable"
  on public.equipment_brochures for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('equipment-brochures', 'equipment-brochures', true)
on conflict (id) do update set public = true;
