create table if not exists public.equipment_photos (
  id bigint generated by default as identity primary key,
  configuration text not null,
  storage_path text not null unique,
  public_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.equipment_photos enable row level security;

drop policy if exists "Public equipment photos are readable" on public.equipment_photos;
create policy "Public equipment photos are readable"
  on public.equipment_photos for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('equipment-photos', 'equipment-photos', true)
on conflict (id) do update set public = true;
